services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: 'jobradar'
      POSTGRES_PASSWORD: 'jobradar'
      POSTGRES_DB: 'todo'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped

volumes:
  postgres_data:
