
"""Added user id column in todos

Revision ID: 1b495cec170c
Revises: 5be27e8cf26b
Create Date: 2026-09-25 21:32:13.814248

"""

from typing import Sequence, Union

from alembic import op

import sqlalchemy as sa



# revision identifiers, used by Alembic.

revision: str = '1b495cec170c'

down_revision: Union[str, Sequence[str], None] = '5be27e8cf26b'

branch_labels: Union[str, Sequence[str], None] = None

depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'todos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'user_id')
    # ### end Alembic commands ###
