## This is a Mako template, not a migration that runs directly.
## Alembic renders this file whenever `alembic revision` creates a new file.
## Mako expressions use the `${...}` syntax and are replaced with values known
## by Alembic for the new revision.

## The generated file begins with a module docstring containing the revision
## message, revision identifier, parent revision, and creation timestamp.
"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""

## Sequence and Union describe revision identifiers that may be a single string,
## multiple strings for merge revisions, or None for the first revision.
from typing import Sequence, Union

## `op` is Alembic's operations interface. Generated migrations use it for
## actions such as `op.create_table`, `op.add_column`, and `op.drop_column`.
from alembic import op

## `sa` is the conventional alias for SQLAlchemy. Generated migrations use it
## to describe columns, types, constraints, indexes, and server defaults.
import sqlalchemy as sa

## Alembic inserts any additional imports required by autogenerate here.
## If no additional imports are needed, this expression renders an empty string.
${imports if imports else ""}

## These four values form Alembic's revision graph metadata.
## They are emitted as Python comments plus typed module-level variables.
# revision identifiers, used by Alembic.

## Unique identifier for this migration. Alembic uses it to locate the revision.
revision: str = ${repr(up_revision)}

## Parent revision. This is normally one revision ID, None for the first
## revision, or a sequence when the migration is a merge point.
down_revision: Union[str, Sequence[str], None] = ${repr(down_revision)}

## Optional branch names used to label migration branches.
branch_labels: Union[str, Sequence[str], None] = ${repr(branch_labels)}

## Optional dependency on another revision that is not this revision's direct
## parent. This is useful when migration branches must be ordered explicitly.
depends_on: Union[str, Sequence[str], None] = ${repr(depends_on)}


## Alembic executes this function when moving the database forward to this
## revision. Autogenerated upgrade operations are inserted into its body.
def upgrade() -> None:
    ## This docstring describes the direction of the operation.
    """Upgrade schema."""
    ## Insert generated upgrade operations here. Use `pass` when no operations
    ## were detected, so the generated function remains valid Python.
    ${upgrades if upgrades else "pass"}


## Alembic executes this function when reverting this revision. It should undo
## the changes made by `upgrade()` whenever a safe reversal is possible.
def downgrade() -> None:
    ## This docstring describes the direction of the operation.
    """Downgrade schema."""
    ## Insert generated downgrade operations here. Use `pass` when no operations
    ## were detected, so the generated function remains valid Python.
    ${downgrades if downgrades else "pass"}
